name:                pl-lib
version:             0.1.0.0
github:              "githubuser/pl-lib"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pl-lib#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy
- polysemy-plugin
- data-fix
- free
- comonad

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin

default-extensions:
- RankNTypes
- TemplateHaskell
- LambdaCase
- ImpredicativeTypes
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- GADTs
- ScopedTypeVariables
- DataKinds
- PolyKinds
- RankNTypes
- TypeApplications
- TypeOperators
- TypeFamilies
- OverloadedRecordDot
- MultiParamTypeClasses
- BlockArguments

library:
  source-dirs: src

executables:
  pl-lib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pl-lib

tests:
  pl-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pl-lib
